# Generated by Django 2.2.6 on 2019-11-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_auto_20191104_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Employee'), (1, 'Normal')], default=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting Verified'), (1, 'Waiting Done'), (2, 'Done'), (3, 'Deleted'), (4, 'Cancelled'), (5, 'Not Verified')], default=0),
        ),
    ]
