# Generated by Django 2.2.6 on 2019-11-05 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_auto_20191105_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('status', models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Done'), (2, 'Active')], default=2)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Topic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
