# Generated by Django 2.2.6 on 2019-11-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_topic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=104, null=True),
        ),
    ]
